cc_test(
    name = "simple-test",
    srcs = ["simple_test.cpp"],
    copts = ["-Iexternal/gtest/include"],
    deps = [
        #        "@gtest//:gtest",
        "@gtest//:gtest_main",
    ],
)

cc_test(
    name = "simple-test-2",
    srcs = ["simple-test-2.cpp"],
    copts = ["-Iexternal/gtest/include"],
    deps = [
        #        "@gtest//:gtest",
        "@gtest//:gtest_main",
    ],
)
